### ISSUE TITLE
Save Library

### ISSUE THREAD

**Issue by wilburlikesmith** [rafaheringer/remo#13]
Hi, I'd love to use this regularly.

I've got two issues but the one is more of a Chrome problem, which I'll mention last.

My Remo issue in short is that it doesn't save my playlist/library. Each time I launch it I have to "Open folder" again. Could or are you looking into that?

Secondly I use the "Continue where I left off" setting under "Startup" in my Chrome's settings, basically "bookmarking" my current tabs. Problem is that if a Chrome App Launcher app is open and I close my browser windows before the Chrome Apps, it discards my open tabs.

Thanks for the app anyway.

**Comment by rafaheringer** [comment]
Hello, I appreciate your feedback!

I'll start thinking about a solution to save the playlist. It sure is a useful and important feature.

The second request is really a problem of Chrome. I'll find some solution and see if there is any way to solve this issue.

(Sorry for my poor english)

**Comment by wilburlikesmith** [comment]
Hey, não há problema. Fico feliz que você respondeu. Meu Português não é muito melhor, mas o Google Translate certeza não ajuda :)

**Comment by rafaheringer** [comment]
Eu criei um branch para este issue: https://github.com/rafaheringer/remo/tree/savePlaylist

Na versão 31 do Chrome será possível utilizar o histórico de arquivos abertos pelo usuário. Será mais fácil completar esse issue.

Mas, por enquanto, estou guardando os arquivos de música no localStorage. Assim que o usuário abre o player, leio os arquivos guardados e recupero eles. Isso é um processo lento, porém funciona. Estou tentando otimizar o processo. 

A meta é fazer o merge com o branch master na próxima semana.

**Comment by wilburlikesmith** [comment]
Isso é tão impressionante, manter o bom trabalho!

w.

_hooloovoo(media)_
design extraordinaire, wearer of many hats

---

"All opinions are not equal. Some are a very great deal more robust,
sophisticated and well supported in logic and argument than others."

 _— Douglas Adams_

2013/10/14 Rafael Heringer notifications@github.com

**Comment by rafaheringer** [comment]
Hey!

A versão já está online! Confira :D Se você já possui o Remo instalado, reinicie o seu navegador para buscar a última atualização do programa.

Obrigado.
